fix: Correct filter inputs
After the upgrade form boto to boto3 this code was causing a
stack trace like the following.

botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in Filters[0]: "key-name", must be one of: Name, Values